### ISSUE TITLE
New Rating Divisions (Div1/Div2) introduced in MARCH18

### ISSUE THREAD

**Issue by sspathare97** [vsp4/codechef-rating-predictor#4]
Rating of each user is calculated based on participants of his division. Please check the post here - https://discuss.codechef.com/questions/123877/new-rating-divisions-div1div2-on-codechef

**Comment by vsp4** [comment]
Rating predictor should most probably work just well because i don't think there is any change in there rating mechanism, it looks like just two different contests for users based on there rating (Div1 users can't submit in div2 and div2 users can't submit in div1)

http://codechef-rating-predictor.7e14.starter-us-west-2.openshiftapps.com/contest/MARCH18A/all
http://codechef-rating-predictor.7e14.starter-us-west-2.openshiftapps.com/contest/MARCH18B/all

The only possible flaw could be in "Non Scorable Problems" like if a users submits solution only for "Non Scorable Problems" and no main problem from contest, it isn't clear whether his participation in contest would be considered for rating change or not.

**Comment by sspathare97** [comment]
Thanks!
